
mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff_3sigma/
mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff_3sigma/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff_3sigma/workspace_preparation/ 
cp workspace_preparation/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff_3sigma/workspace_preparation/

mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff_3sigma/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff_3sigma/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff_3sigma/workspace_plots/


mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff_3sigma/FOM

cp FOM/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff_3sigma/FOM/


mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff_3sigma/compare_fits

cp compare_fits/* ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff_3sigma/compare_fits/
