
mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_add2016_Run1and2015only/
mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_add2016_Run1and2015only/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_add2016_Run1and2015only/workspace_preparation/ 
cp workspace_preparation/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_add2016_Run1and2015only/workspace_preparation/

mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_add2016_Run1and2015only/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_add2016_Run1and2015only/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_add2016_Run1and2015only/workspace_plots/


mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_add2016_Run1and2015only/FOM

cp FOM/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_add2016_Run1and2015only/FOM/
