
mkdir ~/public_html/fitsignalchannelFUMSB_NOTsimultaneous_newcontrolchannel/
mkdir ~/public_html/fitsignalchannelFUMSB_NOTsimultaneous_newcontrolchannel/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignalchannelFUMSB_NOTsimultaneous_newcontrolchannel/workspace_preparation/ 


mkdir ~/public_html/fitsignalchannelFUMSB_NOTsimultaneous_newcontrolchannel/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignalchannelFUMSB_NOTsimultaneous_newcontrolchannel/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignalchannelFUMSB_NOTsimultaneous_newcontrolchannel/workspace_plots/


mkdir ~/public_html/fitsignalchannelFUMSB_NOTsimultaneous_newcontrolchannel/FOM

cp FOM/*txt ~/public_html/fitsignalchannelFUMSB_NOTsimultaneous_newcontrolchannel/FOM/
