
mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_correctses/
mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_correctses/expected_exclusion/

cp -r toy_* ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_correctses/expected_exclusion/ 
cp -r plotExclusionLimit/*pdf ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_correctses/expected_exclusion/ 
