
mkdir ~/public_html/fitcontrol/fitcontrolchannelFUMSB_simultaneous_add2016_scalesig
mkdir ~/public_html/fitcontrol/fitcontrolchannelFUMSB_simultaneous_add2016_scalesig/LowFCME
cp workspace/*pdf ~/public_html/fitcontrol/fitcontrolchannelFUMSB_simultaneous_add2016_scalesig/LowFCME/
