
mkdir ~/public_html/average_misidvariations
mkdir ~/public_html/average_misidvariations/FUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights_2_misidvariation/
mkdir ~/public_html/average_misidvariations/FUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights_2_misidvariation/plots
mkdir ~/public_html/average_misidvariations/FUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights_2_misidvariation/preparation
mkdir ~/public_html/average_misidvariations/FUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights_2_misidvariation/bin_info
cp preparation/*pdf ~/public_html/average_misidvariations/FUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights_2_misidvariation/plots
cp preparation/*txt ~/public_html/average_misidvariations/FUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights_2_misidvariation/preparation/ 
cp bin_info/*pdf ~/public_html/average_misidvariations/FUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights_2_misidvariation/bin_info
cp bin_info/*Summary.txt ~/public_html/average_misidvariations/FUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights_2_misidvariation/bin_info
