
rm ~/public_html/average_misidvariations/FUMSB_simultaneous_NewTCK_misidvariation/plots/*
rm ~/public_html/average_misidvariations/FUMSB_simultaneous_NewTCK_misidvariation/preparation/*
rm ~/public_html/average_misidvariations/FUMSB_simultaneous_NewTCK_misidvariation/bin_info/*


mkdir ~/public_html/average_misidvariations
mkdir ~/public_html/average_misidvariations/FUMSB_simultaneous_NewTCK_misidvariation/
mkdir ~/public_html/average_misidvariations/FUMSB_simultaneous_NewTCK_misidvariation/plots
mkdir ~/public_html/average_misidvariations/FUMSB_simultaneous_NewTCK_misidvariation/preparation
mkdir ~/public_html/average_misidvariations/FUMSB_simultaneous_NewTCK_misidvariation/bin_info
cp preparation/*pdf ~/public_html/average_misidvariations/FUMSB_simultaneous_NewTCK_misidvariation/plots
cp preparation/*txt ~/public_html/average_misidvariations/FUMSB_simultaneous_NewTCK_misidvariation/preparation/ 
cp bin_info/*pdf ~/public_html/average_misidvariations/FUMSB_simultaneous_NewTCK_misidvariation/bin_info
cp bin_info/*Summary.txt ~/public_html/average_misidvariations/FUMSB_simultaneous_NewTCK_misidvariation/bin_info
