
mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_alldata_chi2fit/
mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_alldata_chi2fit/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_alldata_chi2fit/workspace_preparation/ 
cp workspace_preparation/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_alldata_chi2fit/workspace_preparation/

mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_alldata_chi2fit/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_alldata_chi2fit/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_alldata_chi2fit/workspace_plots/


mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_alldata_chi2fit/FOM

cp FOM/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_alldata_chi2fit/FOM/


mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_alldata_chi2fit/compare_fits

cp compare_fits/* ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_alldata_chi2fit/compare_fits/
