
mkdir ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK_newcode2/
mkdir ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK_newcode2/expected_exclusion/

cp -r toy_* ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK_newcode2/expected_exclusion/ 
cp -r plotExclusionLimit/bin/*pdf ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK_newcode2/expected_exclusion/ 
