cp /vols/lhcb/ss4314/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/workspace_preparation/plotMisidFitPretty_.pdf plotMisidFitPretty_Run1.pdf
cp /vols/lhcb/ss4314/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_2016/workspace_preparation/plotMisidFitPretty_.pdf plotMisidFitPretty_2016.pdf
