#!/bin/bash

cp /vols/lhcb/ss4314/preparetuplesforBDTfinalallvartrigger/MCSigpreparetupleNew/bin/Efficiencies.pdf EfficienciesB23muMC.pdf
cp /vols/lhcb/ss4314/preparetuplesforBDTfinalallvartrigger/JpsiKMCDetachedLine/2011/bin/Efficiencies.pdf EfficienciesJpsiKmc2011.pdf
cp /vols/lhcb/ss4314/preparetuplesforBDTfinalallvartrigger/JpsiKMCDetachedLine/2012/bin/Efficiencies.pdf EfficienciesJpsiKmc2012.pdf
cp /vols/lhcb/ss4314/cutonBDTs/MCnonsharedvsCombiFUMSB_newcontrolchannel/bin/EfficienciesCombiBDT.pdf EfficienciesCombiBDT.pdf
cp /vols/lhcb/ss4314/cutonBDTs/MCnonsharedvsMisidFUMSB_newcontrolchannel/bin/EfficienciesMisidBDT.pdf EfficienciesMISID.pdf
cp /vols/lhcb/ss4314/cutonFitRange/FUMSB_simultaneous_symmetric_newcontrolchannel/bin/EfficienciesFitRange.pdf EfficienciesFitRange.pdf
cp /vols/lhcb/ss4314/cutonFCME/FUMSB_simultaneous_symmetric_newcontrolchannel/bin/EfficienciesLFCME.pdf EfficienciesLCFME.pdf
cp /vols/lhcb/ss4314/cutonFCME/FUMSB_simultaneous_symmetric_newcontrolchannel/bin/EfficienciesHFCME.pdf EfficienciesHCFME.pdf
cp /vols/lhcb/ss4314/fitcontrolchannelFUMSB_simultaneous_symmetric_newcontrolchannel/LowFCME/workspace/plotJpsiKFit.pdf JpsikdatalowFCME.pdf
cp /vols/lhcb/ss4314/fitcontrolchannelFUMSB_simultaneous_symmetric_newcontrolchannel/HighFCME/workspace/plotJpsiKFit.pdf JpsikdatahighFCME.pdf
cp /vols/lhcb/ss4314/fitcontrolchannelFUMSB_simultaneous_symmetric_newcontrolchannel/LowFCME/workspace/HypathiaplotJpsiK.pdf JpsikdatalowFCMEHypathia.pdf
cp /vols/lhcb/ss4314/fitcontrolchannelFUMSB_simultaneous_symmetric_newcontrolchannel/HighFCME/workspace/HypathiaplotJpsiK.pdf JpsikdatahighFCMEHypathia.pdf
cp /vols/lhcb/ss4314/PIDeffMC/FUMSB_simultaneous_symmetric_newcontrolchannel/MCsigB23Mu/bin/PIDEfficiency_BASICUTSMagDownStrip21LowFCME.tex EfficiencyPIDB23MuLowFCME.tex
cp /vols/lhcb/ss4314/PIDeffMC/FUMSB_simultaneous_symmetric_newcontrolchannel/MCsigB23Mu/bin/PIDEfficiency_BASICUTSMagDownStrip21HighFCME.tex EfficiencyPIDB23MuHighFCME.tex
cp /vols/lhcb/ss4314/cutonFCME/FUMSB_simultaneous_symmetric_newcontrolchannel/bin/EfficienciesLFCME.pdf crosschecksigLowFCME.pdf
cp /vols/lhcb/ss4314/cutonFCME/FUMSB_simultaneous_symmetric_newcontrolchannel/bin/EfficienciesHFCME.pdf crosschecksigHighFCME.pdf
cp /vols/lhcb/ss4314/PIDeffMC/FUMSB_simultaneous_symmetric_newcontrolchannel/MCctlJpsiK/bin/PIDEfficiency_BASICUTSMagDownStrip21LowFCME.tex EfficiencyPIDJpsiKLowFCME.tex
cp /vols/lhcb/ss4314/PIDeffMC/FUMSB_simultaneous_symmetric_newcontrolchannel/MCctlJpsiK/bin/PIDEfficiency_BASICUTSMagDownStrip21HighFCME.tex EfficiencyPIDJpsiKHighFCME.tex
