cp /home/hep/ss4314/public_html/fitcontrol/fitcontrolchannelFUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights/probnnmu035/NOFCME/HypatiaplotJpsiKFitLogyPrettyRun1.pdf HypatiaplotJpsiKFitLogyPrettyRun1NOFCME.pdf
cp /home/hep/ss4314/public_html/fitcontrol/fitcontrolchannelFUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights/2016_probmu35/NOFCME/HypatiaplotJpsiKFitLogyPretty2016.pdf HypatiaplotJpsiKFitLogyPretty2016NOFCME.pdf

cp /home/hep/ss4314/public_html/fitcontrol/fitcontrolchannelFUMSB_simultaneous_NewTCK_PIDoptimisation_extremeweights/probnnmu035/LowFCME/HypatiaplotJpsiKFitLogyPrettyRun1.pdf HypatiaplotJpsiKFitLogyPrettyRun1lowFCME.pdf
cp /home/hep/ss4314/public_html/fitcontrol/fitcontrolchannelFUMSB_simultaneous_NewTCK_PIDoptimisation_extremeweights/2016_probmu35/LowFCME/HypatiaplotJpsiKFitLogyPretty2016.pdf HypatiaplotJpsiKFitLogyPretty2016lowFCME.pdf

cp /home/hep/ss4314/public_html/fitcontrol/fitcontrolchannelFUMSB_simultaneous_NewTCK_PIDoptimisation_extremeweights/probnnmu035/HighFCME/HypatiaplotJpsiKFitLogyPrettyRun1.pdf HypatiaplotJpsiKFitLogyPrettyRun1highFCME.pdf
cp /home/hep/ss4314/public_html/fitcontrol/fitcontrolchannelFUMSB_simultaneous_NewTCK_PIDoptimisation_extremeweights/2016_probmu35/HighFCME/HypatiaplotJpsiKFitLogyPretty2016.pdf HypatiaplotJpsiKFitLogyPretty2016highFCME.pdf

cp /vols/lhcb/ss4314/fitcontrol/fitcontrolchannelFUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights/NOFCME/workspace/CORRECTEDFORANApimumuANA035.pdf WeightedFitToPimumuANA.pdf 

cp /vols/lhcb/ss4314/fitcontrol/fitcontrolchannelFUMSB_NOTsimultaneous_NewTCK_PIDoptimisation_extremeweights/NOFCME/workspace/mcsigfit_HYP_NOTMAIN_LOGY_moreinfo_Run1.pdf .
