#cp /vols/lhcb/ss4314/SingleEventSensitivity/SesFUMSB_simultaneous_NewTCK_neweffcalc/plot_interesting/bin/Plot_ALL_Efficiencies_Overview_lowFCME.pdf .
#cp /vols/lhcb/ss4314/SingleEventSensitivity/SesFUMSB_simultaneous_NewTCK_neweffcalc/plot_interesting/bin/Plot_ALL_Efficiencies_Overview_highFCME.pdf .
cp /vols/lhcb/ss4314/tablesforana/efficiencyratios/2016/SesFUMSB_NOTsimultaneous_full_Error/plot_interesting/bin/Plot_ALL_Efficiencies_Overview_Pretty.pdf Plot_ALL_Efficiencies_Overview_NOFCME_Pretty.pdf

cp /vols/lhcb/ss4314/SingleEventSensitivity/SesFUMSB_NOTsimultaneous_final_optimisation_GenLevelEff/plot_interesting/bin/Plot_ALL_Efficiencies_Overview.pdf Plot_ALL_Efficiencies_Overview_NOFCME.pdf
