cp /vols/lhcb/ss4314/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/workspace_plots/probnnmu035plotB23MuNuFitPretty_chi2_Overlay.pdf overlay_nonsim.pdf
cp /vols/lhcb/ss4314/fitsignal/fitsignal_simultaneous_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/workspace_plots/HighFCMEprobnnmu035plotB23MuNuFitPretty_chi2_overlay.pdf overlay_highsim.pdf
cp /vols/lhcb/ss4314/fitsignal/fitsignal_simultaneous_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/workspace_plots/LowFCMEprobnnmu035plotB23MuNuFitPretty_chi2_overlay.pdf overlay_lowsim.pdf
