
mkdir ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK/
mkdir ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK/expected_exclusion/

cp -r toy_* ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK/expected_exclusion/ 
cp -r plotExclusionLimit/bin/*pdf ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK/expected_exclusion/ 
