#!/bin/bash

cp /vols/lhcb/ss4314/preparetuplesforBDTfinalallvartrigger/MCSigpreparetupleNew/bin/Efficiencies.pdf EfficienciesB23muMC.pdf
cp /vols/lhcb/ss4314/preparetuplesforBDTfinalallvartrigger/JpsiKmc2011strip20r1New/bin/Efficiencies.pdf EfficienciesJpsiKmc2011.pdf
cp /vols/lhcb/ss4314/preparetuplesforBDTfinalallvartrigger/JpsiKmcNew/bin/Efficiencies.pdf EfficienciesJpsiKmc2012.pdf
cp /vols/lhcb/ss4314/cutonBDTs/MCnonsharedvsCombiFUMSB/numofeventsleftintuples.pdf numofeventsleftintuplesCOMBI.pdf
cp /vols/lhcb/ss4314/cutonBDTs/MCnonsharedvsMisidFUMSB/numofeventsleftintuples.pdf numofeventsleftintuplesMISID.pdf
cp /vols/lhcb/ss4314/cutonBDTs/MCnonsharedvsCombiFUMSB/EfficienciesCombiBDT.pdf EfficienciesCOMBI.pdf
cp /vols/lhcb/ss4314/cutonBDTs/MCnonsharedvsMisidFUMSB/EfficienciesMisidBDT.pdf EfficienciesMISID.pdf
cp /vols/lhcb/ss4314/cutonFitRange/FUMSB_simultaneous_symmetric/EfficienciesCorM.pdf EfficienciesCorM.pdf
cp /vols/lhcb/ss4314/cutonFCME/FUMSB_simultaneous_symmetric/EfficienciesLCFME.pdf EfficienciesLCFME.pdf
cp /vols/lhcb/ss4314/cutonFCME/FUMSB_simultaneous_symmetric/EfficienciesHCFME.pdf EfficienciesHCFME.pdf
cp /vols/lhcb/ss4314/fitcontrolchannelFUMSB_simultaneous_symmetric/LowFCME/workspace/plotJpsiKFit.pdf JpsikdatalowFCME.pdf
cp /vols/lhcb/ss4314/fitcontrolchannelFUMSB_simultaneous_symmetric/HighFCME/workspace/plotJpsiKFit.pdf JpsikdatahighFCME.pdf
cp /vols/lhcb/ss4314/PIDeffMC/FUMSB_simultaneous_symmetric/MCsigB23Mu/bin/PIDEfficiency_BASICUTSMagDownStrip21LowFCME.tex EfficiencyPIDB23MuLowFCME.tex
cp /vols/lhcb/ss4314/PIDeffMC/FUMSB_simultaneous_symmetric/MCsigB23Mu/bin/PIDEfficiency_BASICUTSMagDownStrip21HighFCME.tex EfficiencyPIDB23MuHighFCME.tex
cp /vols/lhcb/ss4314/cutonFCME/FUMSB_simultaneous_symmetric/numofeventsleftintuplesLCFME.pdf crosschecksigLowFCME.pdf
cp /vols/lhcb/ss4314/cutonFCME/FUMSB_simultaneous_symmetric/numofeventsleftintuplesHCFME.pdf crosschecksigHighFCME.pdf
cp /vols/lhcb/ss4314/PIDeffMC/FUMSB_simultaneous_symmetric/MCctlJpsiK/bin/PIDEfficiency_BASICUTSMagDownStrip21LowFCME.tex EfficiencyPIDJpsiKLowFCME.tex
cp /vols/lhcb/ss4314/PIDeffMC/FUMSB_simultaneous_symmetric/MCctlJpsiK/bin/PIDEfficiency_BASICUTSMagDownStrip21HighFCME.tex EfficiencyPIDJpsiKHighFCME.tex
