
mkdir ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only/
mkdir ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only/workspace_preparation/ 
cp workspace_preparation/*txt ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only/workspace_preparation/

mkdir ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only/workspace_plots/


mkdir ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only/FOM

cp FOM/*txt ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only/FOM/

mkdir ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only/compare_fits

cp compare_fits/* ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only/compare_fits/
