
mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_add2016_scalesig_finer/
mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_add2016_scalesig_finer/expected_exclusion/

cp -r toy_* ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_add2016_scalesig_finer/expected_exclusion/ 
cp -r plotExclusionLimit/bin/*pdf ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_add2016_scalesig_finer/expected_exclusion/ 
