mkdir ~/public_html/jpsikststudy/PIDCalibTables/kaonmisid/jackbinandinmuonagainchangeorderunbiasbyhand
cp PIDResult/*txt ~/public_html/jpsikststudy/PIDCalibTables/kaonmisid/jackbinandinmuonagainchangeorderunbiasbyhand
