mkdir ~/public_html/fitjpsikst
mkdir ~/public_html/fitjpsikst/fitjpsikst_lambdapkmumu_idPION_coarsebin/KisMuonandNSharedProbnnmu
mkdir ~/public_html/fitjpsikst/fitjpsikst_lambdapkmumu_idPION_coarsebin/KisMuonandNSharedProbnnmu
mkdir ~/public_html/fitjpsikst/fitjpsikst_lambdapkmumu_idPION_coarsebin/KisMuonandNSharedProbnnmu/NOFCME
cp workspace/*pdf ~/public_html/fitjpsikst/fitjpsikst_lambdapkmumu_idPION_coarsebin/KisMuonandNSharedProbnnmu/NOFCME/
mkdir ~/public_html/fitjpsikst/fitjpsikst_lambdapkmumu_idPION_coarsebin/KisMuonandNSharedProbnnmu/PIDtable/
cp PIDResult/*txt ~/public_html/fitjpsikst/fitjpsikst_lambdapkmumu_idPION_coarsebin/KisMuonandNSharedProbnnmu/PIDtable/
mkdir ~/public_html/fitjpsikst/fitjpsikst_lambdapkmumu_idPION_coarsebin/KisMuonandNSharedProbnnmu/MergedFits/
cp MergedFits/*pdf ~/public_html/fitjpsikst/fitjpsikst_lambdapkmumu_idPION_coarsebin/KisMuonandNSharedProbnnmu/MergedFits/
