/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYCB
#define MYCB

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyCB : public RooAbsPdf {
public:
  MyCB() {} ; 
  MyCB(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma,
	      RooAbsReal& _al,
	      RooAbsReal& _nl,
	      RooAbsReal& _ar,
	      RooAbsReal& _nr);
  MyCB(const MyCB& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyCB(*this,newname); }
  inline virtual ~MyCB() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy al ;
  RooRealProxy nl ;
  RooRealProxy ar ;
  RooRealProxy nr ;
  
  Double_t evaluate() const ;

private:

//  ClassDef(MyCB,1) // Your description goes here...
};
 
#endif
