mkdir ~/public_html/fitsignal_before_misidbdt
mkdir ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/
mkdir ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/workspace_preparation/ 
cp workspace_preparation/*txt ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/workspace_preparation/
cp WARNING.txt ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/

mkdir ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/workspace_plots
mkdir ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/misid_shapes_nocross_andcross

cp workspace_plots/*pdf ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/workspace_plots/
cp misid_shapes_nocross_andcross/*pdf ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/misid_shapes_nocross_andcross/


mkdir ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/FOM

cp FOM/*txt ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/FOM/

mkdir  ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/misid_shapes_nocross_andcross/

cp misid_shapes_nocross_andcross/*pdf   ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_finalPID_Run1/misid_shapes_nocross_andcross/
