
mkdir ~/public_html/prepare_misidvariations
mkdir ~/public_html/prepare_misidvariations/FUMSB_NOTsimultaneous_NewTCK_misidvariation_extremeweights_2/
cp generatedplots/*pdf ~/public_html/prepare_misidvariations/FUMSB_NOTsimultaneous_NewTCK_misidvariation_extremeweights_2/
