
cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_KAONMISID_2012_ALT_BINNING.root originaltuples/
cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_PIONMISID_2012_ALT_BINNING.root originaltuples/

cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_KAONMISID_2016_ALT_BINNING.root originaltuples/
cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_PIONMISID_2016_ALT_BINNING.root originaltuples/

cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_KAONMISID_2011_ALT_BINNING.root originaltuples/
cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_PIONMISID_2011_ALT_BINNING.root originaltuples/


cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDeff_myowntuples_OPTI/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_KAONMISID_2012_ALT_BINNING.root originaltuples_2/
cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDeff_myowntuples_OPTI/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_PIONMISID_2012_ALT_BINNING.root originaltuples_2/

cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDeff_myowntuples_OPTI/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_KAONMISID_2016_ALT_BINNING.root originaltuples_2/
cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDeff_myowntuples_OPTI/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_PIONMISID_2016_ALT_BINNING.root originaltuples_2/

cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDeff_myowntuples_OPTI/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_KAONMISID_2011_ALT_BINNING.root originaltuples_2/
cp /vols/lhcb/ss4314/PIDeff_myowntuples/PIDeff_myowntuples_OPTI/PIDrebinnedtuples/PID_2D_ALL_INFO_FORANALYSIS_PIONMISID_2011_ALT_BINNING.root originaltuples_2/
