
mkdir ~/public_html/fitcontrol/fitcontrolchannelFUMSB_simultaneous_add2016
mkdir ~/public_html/fitcontrol/fitcontrolchannelFUMSB_simultaneous_add2016/HighFCME
cp workspace/*pdf ~/public_html/fitcontrol/fitcontrolchannelFUMSB_simultaneous_add2016/HighFCME/
