
mkdir SesFUMSB_NOTsimultaneous_final_optimisation_GenLevelEff
cp -r /vols/lhcb/ss4314/SingleEventSensitivity/SesFUMSB_NOTsimultaneous_final_optimisation_GenLevelEff/* SesFUMSB_NOTsimultaneous_final_optimisation_GenLevelEff/
