
cp /home/hep/ss4314/public_html/fitsignal/fitsignal_simultaneous_final_genlevelcor_allsyst/probnnmu035probmu35/workspace_plots/HighFCMEprobnnmu035probmu35plotB23MuNuFitPretty_chi2_reallynice.pdf .

cp /home/hep/ss4314/public_html/fitsignal/fitsignal_simultaneous_final_genlevelcor_allsyst/probnnmu035probmu35/workspace_plots/LowFCMEprobnnmu035probmu35plotB23MuNuFitPretty_chi2_reallynice.pdf .

cp /home/hep/ss4314/public_html/fitsignal/fitsignal_final_genlevelcor_allsyst/probnnmu035probmu35/workspace_plots/probnnmu035probmu35plotB23MuNuFitPretty_chi2_reallynice.pdf .
