mkdir ~/public_html/fitsignal_before_misidbdt
mkdir ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_newTCK_2016/
mkdir ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_newTCK_2016/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_newTCK_2016/workspace_preparation/ 
cp workspace_preparation/*txt ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_newTCK_2016/workspace_preparation/

mkdir ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_newTCK_2016/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_newTCK_2016/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_newTCK_2016/workspace_plots/


mkdir ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_newTCK_2016/FOM

cp FOM/*txt ~/public_html/fitsignal_before_misidbdt/estimateformisidbdt_newTCK_2016/FOM/
