cp /vols/lhcb/ss4314/fitcontrol/fitcontrolchannelFUMSB_NOTsimultaneous_NewTCK/NOFCME/workspace/HypatiaplotJpsiKFitLogyPrettyRun1.pdf HypatiaplotJpsiKFitLogyPrettyRun1NOFCME.pdf
cp /vols/lhcb/ss4314/fitcontrol/fitcontrolchannelFUMSB_NOTsimultaneous_NewTCK/NOFCME/workspace/HypatiaplotJpsiKFitLogyPretty2016.pdf HypatiaplotJpsiKFitLogyPretty2016NOFCME.pdf

cp /vols/lhcb/ss4314/fitcontrol/fitcontrolchannelFUMSB_simultaneous_NewTCK/LowFCME/workspace/HypatiaplotJpsiKFitLogyPrettyRun1.pdf HypatiaplotJpsiKFitLogyPrettyRun1lowFCME.pdf
cp /vols/lhcb/ss4314/fitcontrol/fitcontrolchannelFUMSB_simultaneous_NewTCK/LowFCME/workspace/HypatiaplotJpsiKFitLogyPretty2016.pdf HypatiaplotJpsiKFitLogyPretty2016lowFCME.pdf

cp /vols/lhcb/ss4314/fitcontrol/fitcontrolchannelFUMSB_simultaneous_NewTCK/HighFCME/workspace/HypatiaplotJpsiKFitLogyPrettyRun1.pdf HypatiaplotJpsiKFitLogyPrettyRun1highFCME.pdf
cp /vols/lhcb/ss4314/fitcontrol/fitcontrolchannelFUMSB_simultaneous_NewTCK/HighFCME/workspace/HypatiaplotJpsiKFitLogyPretty2016.pdf HypatiaplotJpsiKFitLogyPretty2016highFCME.pdf

cp /vols/lhcb/ss4314/fitcontrol/fitcontrolchannelFUMSB_NOTsimultaneous_NewTCK/NOFCME/workspace/WeightedFitToPimumuANA.pdf .

cp /vols/lhcb/ss4314/fitcontrol/fitcontrolchannelFUMSB_NOTsimultaneous_NewTCK/NOFCME/workspace/mcsigfit_HYP_NOTMAIN_LOGY_moreinfo_Run1.pdf .
