cp /vols/lhcb/ss4314/plotting_tools/plot_shapes_before_combibdt/bin/plotvariableBplus_pmu_ISOLATION_BDT1_weightsNORMALISATION_ISOLATION_NICE_RUN1.pdf .
cp /vols/lhcb/ss4314/plotting_tools/plot_shapes_before_combibdt/bin/plotvariableBplus_pmu_ISOLATION_BDT1_weightsNORMALISATION_ISOLATION_NICE_2016.pdf .

