
mkdir /home/hep/ss4314/public_html/SingelEventSensitivity/SesFUMSB_simultaneous_NewTCK_neweffcalc/plot_interesting
cp bin/*pdf /home/hep/ss4314/public_html/SingelEventSensitivity/SesFUMSB_simultaneous_NewTCK_neweffcalc/plot_interesting/
