
#//--------copy all relevant tables ----------//


cp /vols/lhcb/ss4314/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/NOFCME/PIDtables/PID_2D_ALL_INFO_FORANALYSIS_KAONMISID_2011.root .
cp /vols/lhcb/ss4314/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/NOFCME/PIDtables/PID_2D_ALL_INFO_FORANALYSIS_PIONMISID_2011.root .


cp /vols/lhcb/ss4314/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/NOFCME/PIDtables/PID_2D_ALL_INFO_FORANALYSIS_KAONMISID_2012.root .
cp /vols/lhcb/ss4314/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/NOFCME/PIDtables/PID_2D_ALL_INFO_FORANALYSIS_PIONMISID_2012.root .


cp /vols/lhcb/ss4314/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/NOFCME/PIDtables/PID_2D_ALL_INFO_FORANALYSIS_KAONMISID_2016.root .
cp /vols/lhcb/ss4314/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/NOFCME/PIDtables/PID_2D_ALL_INFO_FORANALYSIS_PIONMISID_2016.root .
