
mkdir ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK_misidvariation_newcalceff/
mkdir ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK_misidvariation_newcalceff/expected_exclusion/

cp -r toy_* ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK_misidvariation_newcalceff/expected_exclusion/ 
cp -r bin/*pdf ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK_misidvariation_newcalceff/expected_exclusion/ 
cp -r plotExclusionLimit/bin/*pdf ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_simultaneous_NewTCK_misidvariation_newcalceff/expected_exclusion/ 
