mkdir ~/public_html/fitsignal_before_combibdt
mkdir ~/public_html/fitsignal_before_combibdt/estimateforcombibdt_newTCK_Run1/
mkdir ~/public_html/fitsignal_before_combibdt/estimateforcombibdt_newTCK_Run1/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignal_before_combibdt/estimateforcombibdt_newTCK_Run1/workspace_preparation/ 
cp workspace_preparation/*txt ~/public_html/fitsignal_before_combibdt/estimateforcombibdt_newTCK_Run1/workspace_preparation/

mkdir ~/public_html/fitsignal_before_combibdt/estimateforcombibdt_newTCK_Run1/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignal_before_combibdt/estimateforcombibdt_newTCK_Run1/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignal_before_combibdt/estimateforcombibdt_newTCK_Run1/workspace_plots/


mkdir ~/public_html/fitsignal_before_combibdt/estimateforcombibdt_newTCK_Run1/FOM

cp FOM/*txt ~/public_html/fitsignal_before_combibdt/estimateforcombibdt_newTCK_Run1/FOM/
