
mkdir ~/public_html/fitsignalchannelFUMSB_simultaneous_correctses_freeexpcon/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignalchannelFUMSB_simultaneous_correctses_freeexpcon/workspace_preparation/ 


mkdir ~/public_html/fitsignalchannelFUMSB_simultaneous_correctses_freeexpcon/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignalchannelFUMSB_simultaneous_correctses_freeexpcon/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignalchannelFUMSB_simultaneous_correctses_freeexpcon/workspace_plots/


mkdir ~/public_html/fitsignalchannelFUMSB_simultaneous_correctses_freeexpcon/FOM

cp FOM/*txt ~/public_html/fitsignalchannelFUMSB_simultaneous_correctses_freeexpcon/FOM/
