mkdir ~/public_html/fitjpsikst
mkdir ~/public_html/fitjpsikst/fitjpsikst_idPIONsofter_jackbin/
mkdir ~/public_html/fitjpsikst/fitjpsikst_idPIONsofter_jackbin/KisMuonandNSharedProbnnmu
mkdir ~/public_html/fitjpsikst/fitjpsikst_idPIONsofter_jackbin/KisMuonandNSharedProbnnmu
mkdir ~/public_html/fitjpsikst/fitjpsikst_idPIONsofter_jackbin/KisMuonandNSharedProbnnmu/NOFCME
cp workspace/*pdf ~/public_html/fitjpsikst/fitjpsikst_idPIONsofter_jackbin/KisMuonandNSharedProbnnmu/NOFCME/
mkdir ~/public_html/fitjpsikst/fitjpsikst_idPIONsofter_jackbin/KisMuonandNSharedProbnnmu/PIDtable/
cp PIDResult/*txt ~/public_html/fitjpsikst/fitjpsikst_idPIONsofter_jackbin/KisMuonandNSharedProbnnmu/PIDtable/
mkdir ~/public_html/fitjpsikst/fitjpsikst_idPIONsofter_jackbin/KisMuonandNSharedProbnnmu/MergedFits/
cp MergedFits/*pdf ~/public_html/fitjpsikst/fitjpsikst_idPIONsofter_jackbin/KisMuonandNSharedProbnnmu/MergedFits/
