
hadd -f mergedTuples/Data_Run1_unblinded.root bin/Data_B23MuNu_Run1_lmsbregion_trigger_Jpsi_mu1nShared_mu2nShared_mu3nShared_qmincut_CombBasic_MisidBasic_FitCorM_probnnmu035.root bin/Data_B23MuNu_Run1_sigregion_trigger_Jpsi_mu1nShared_mu2nShared_mu3nShared_qmincut_CombBasic_MisidBasic_FitCorM_probnnmu035.root bin/Data_B23MuNu_Run1_umsbregion_trigger_Jpsi_mu1nShared_mu2nShared_mu3nShared_qmincut_CombBasic_MisidBasic_FitCorM_probnnmu035.root

