
mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_add2015_no2015/
mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_add2015_no2015/expected_exclusion/

cp -r toy_* ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_add2015_no2015/expected_exclusion/ 
cp -r plotExclusionLimit/*pdf ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_simultaneous_add2015_no2015/expected_exclusion/ 
