cp /vols/lhcb/ss4314/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_NewTCK_misidvariation_newcalceff/workspace_preparation/mcsigfit_NOTMAIN_moreinfo_.pdf mcsigfit_NOTMAIN_moreinfo_NOFCME.pdf

cp /vols/lhcb/ss4314/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff/workspace_preparation/mcsigfit_NOTMAIN_moreinfo_HighFCME.pdf .
cp /vols/lhcb/ss4314/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff/workspace_preparation/mcsigfit_NOTMAIN_moreinfo_LowFCME.pdf .
