mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_ADDPDF/
mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_ADDPDF/expected_exclusion/

cp -r toy_* ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_ADDPDF/expected_exclusion/ 
cp -r plotExclusionLimit/*pdf ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_ADDPDF/expected_exclusion/ 
