
mkdir ~/public_html/fitcontrolchannelFUMSB_simultaneous_symmetric_newcontrolchannel
mkdir ~/public_html/fitcontrolchannelFUMSB_simultaneous_symmetric_newcontrolchannel/LowFCME
cp workspace/*pdf ~/public_html/fitcontrolchannelFUMSB_simultaneous_symmetric_newcontrolchannel/LowFCME/
