mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_add2016_scalesig/
mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_add2016_scalesig/expected_exclusion/

cp -r toy_* ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_add2016_scalesig/expected_exclusion/ 
cp -r plotExclusionLimit/*pdf ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_add2016_scalesig/expected_exclusion/ 
