mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_add2016_scalesig_Run1only/
mkdir ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_add2016_scalesig_Run1only/expected_exclusion/

cp -r toy_* ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_add2016_scalesig_Run1only/expected_exclusion/ 
cp -r plotExclusionLimit/*pdf ~/public_html/CLsmethod/fitallafterMCnSharedRemovedFullUMSBIncludeLMSB_NOTsimultaneous_add2016_scalesig_Run1only/expected_exclusion/ 
