
mkdir ~/public_html/fitsignalchannelFUMSB_simultaneous_symmetric_nojackweight/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignalchannelFUMSB_simultaneous_symmetric_nojackweight/workspace_preparation/ 


mkdir ~/public_html/fitsignalchannelFUMSB_simultaneous_symmetric_nojackweight/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignalchannelFUMSB_simultaneous_symmetric_nojackweight/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignalchannelFUMSB_simultaneous_symmetric_nojackweight/workspace_plots/


mkdir ~/public_html/fitsignalchannelFUMSB_simultaneous_symmetric_nojackweight/FOM

cp FOM/*txt ~/public_html/fitsignalchannelFUMSB_simultaneous_symmetric_nojackweight/FOM/
