cp /vols/lhcb/ss4314/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_NewTCK_misidvariation_newcalceff/workspace_plots/plotB23MuNuFitPretty_chi2.pdf plotB23MuNuFitPretty_chi2_NOFCME.pdf
cp /vols/lhcb/ss4314/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff/workspace_plots/LowFCMEplotB23MuNuFitPretty_chi2.pdf .
cp /vols/lhcb/ss4314/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff/workspace_plots/HighFCMEplotB23MuNuFitPretty_chi2.pdf .
