#!/bin/bash

#rm *.root *.pdf

VAR1=Strip21r1
VAR2=MagUp

./main Strip21r1 /vols/lhcb/ss4314/final_tuples_analyser/mc/jpsikst_mc/2011/bin/B2JpsiKstMC_2011_MCTruth_newtrigger_Jpsi_relevantcutsNOGHOSTPROB_KstVeto_JpsiKveto_phiveto_ptcut_PionAsMuon1Hyp_PionAsMuon2Hyp_KaonAsMuon1Hyp_KaonAsMuon2Hyp_muonptcut.root Bd2JpsiKstMC2011.root Bd2JpsiKstMC2011_weights

./main Strip21r1 /vols/lhcb/ss4314/final_tuples_analyser/mc/lambdab2pkmumu_mc/2011/bin/LambdaB2mumupKMC_2011_MCtm_newtrigger_Jpsi_relevantcutsNOGHOSTPROB_KstVeto_JpsiKveto_phiveto_ptcut_PionAsMuon1Hyp_PionAsMuon2Hyp_KaonAsMuon1Hyp_KaonAsMuon2Hyp_muonptcut.root LambdaB2jpsiK2011MC_MCtm.root LambdaB2jpsiK2011MC_MCtm_weights

./main Strip21r1 /vols/lhcb/ss4314/final_tuples_analyser/mc/jpsikst_PiKswaps_mc/2011/bin/B2JpsiKstMC_2011_MCTruth_KPiswap_newtrigger_Jpsi_relevantcutsNOGHOSTPROB_KstVeto_JpsiKveto_phiveto_ptcut_PionAsMuon1Hyp_PionAsMuon2Hyp_KaonAsMuon1Hyp_KaonAsMuon2Hyp_muonptcut.root Bd2JpsiKstMC2011_MCTruth_KPiswap.root Bd2JpsiKstMC2011_MCTruth_KPiswap_weights

./mainforpionweights Strip21r1 /vols/lhcb/ss4314/final_tuples_analyser/mc/jpsikst_mc/2011/bin/B2JpsiKstMC_2011_MCTruth_newtrigger_Jpsi_relevantcutsNOGHOSTPROB_KstVeto_JpsiKveto_phiveto_ptcut_PionAsMuon1Hyp_PionAsMuon2Hyp_KaonAsMuon1Hyp_KaonAsMuon2Hyp_muonptcut.root Bd2JpsiKstMC2011pion.root Bd2JpsiKstMC2011_pionweights

./mainforpionweights Strip21r1 /vols/lhcb/ss4314/final_tuples_analyser/mc/lambdab2pkmumu_mc/2011/bin/LambdaB2mumupKMC_2011_MCtm_newtrigger_Jpsi_relevantcutsNOGHOSTPROB_KstVeto_JpsiKveto_phiveto_ptcut_PionAsMuon1Hyp_PionAsMuon2Hyp_KaonAsMuon1Hyp_KaonAsMuon2Hyp_muonptcut.root LambdaB2jpsiK2011MC_MCtmpion.root LambdaB2jpsiK2011MC_MCtm_pionweights

./mainforpionweights Strip21r1 /vols/lhcb/ss4314/final_tuples_analyser/mc/jpsikst_PiKswaps_mc/2011/bin/B2JpsiKstMC_2011_MCTruth_KPiswap_newtrigger_Jpsi_relevantcutsNOGHOSTPROB_KstVeto_JpsiKveto_phiveto_ptcut_PionAsMuon1Hyp_PionAsMuon2Hyp_KaonAsMuon1Hyp_KaonAsMuon2Hyp_muonptcut.root Bd2JpsiKstMC2011_MCTruth_KPiswappion.root Bd2JpsiKstMC2011_MCTruth_KPiswap_pionweights
#./main Strip21r1 MagDown

#./main Strip21r1r1 MagUp

#./main Strip21r1r1 MagDown

