#cp /vols/lhcb/ss4314/fitsignal/fitsignalchannelFUMSB_NOTsimultaneous_NewTCK_misidvariation_newcalceff/workspace_plots/plotB23MuNuFitPretty_chi2.pdf plotB23MuNuFitPretty_chi2_NOFCME.pdf
#cp /vols/lhcb/ss4314/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff/workspace_plots/LowFCMEplotB23MuNuFitPretty_chi2.pdf .
#cp /vols/lhcb/ss4314/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_newcalceff/workspace_plots/HighFCMEplotB23MuNuFitPretty_chi2.pdf .



cp /vols/lhcb/ss4314/fitsignal/fitsignal_final_genlevelcor_allsyst/workspace_plots/probnnmu035probmu35plotB23MuNuFitPretty_chi2.pdf plotB23MuNuFitPretty_chi2_NOFCME.pdf
cp /vols/lhcb/ss4314/fitsignal/fitsignal_simultaneous_final_genlevelcor_allsyst/workspace_plots/LowFCMEprobnnmu035probmu35plotB23MuNuFitPretty_chi2.pdf LowFCMEplotB23MuNuFitPretty_chi2.pdf 
cp /vols/lhcb/ss4314/fitsignal/fitsignal_simultaneous_final_genlevelcor_allsyst/workspace_plots/HighFCMEprobnnmu035probmu35plotB23MuNuFitPretty_chi2.pdf HighFCMEplotB23MuNuFitPretty_chi2.pdf
