
mkdir ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/
mkdir ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/workspace_preparation/ 
cp workspace_preparation/*txt ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/workspace_preparation/

mkdir ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/workspace_plots/


mkdir ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/FOM

cp FOM/*txt ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/FOM/

mkdir ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/compare_fits

cp compare_fits/* ~/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_Run1only_AntiBDT/compare_fits/
