mkdir ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_NOTsimultaneous_final_GenLevelEff_Run1only/
mkdir ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_NOTsimultaneous_final_GenLevelEff_Run1only/expected_exclusion/

cp bin/*pdf ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_NOTsimultaneous_final_GenLevelEff_Run1only/expected_exclusion/
cp bin/*txt ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_NOTsimultaneous_final_GenLevelEff_Run1only/expected_exclusion/
cp -r toy_* ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_NOTsimultaneous_final_GenLevelEff_Run1only/expected_exclusion/ 
cp -r plotExclusionLimit/bin/*pdf ~/public_html/CLsmethod/expectedlimits_includemisiduncertainites_FullUMSB_NOTsimultaneous_final_GenLevelEff_Run1only/expected_exclusion/ 
