
mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_mvg/
mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_mvg/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_mvg/workspace_preparation/ 
cp workspace_preparation/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_mvg/workspace_preparation/

mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_mvg/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_mvg/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_mvg/workspace_plots/


mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_mvg/FOM

cp FOM/*txt ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_mvg/FOM/


mkdir ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_mvg/compare_fits

cp compare_fits/* ~/public_html/fitsignal/fitsignalchannelFUMSB_simultaneous_NewTCK_misidvariation_mvg/compare_fits/
