
mkdir ~/public_html/fitsignal_unblinding/fitsignal_final_genlevelcor_allsyst_upgrade/
mkdir ~/public_html/fitsignal_unblinding/fitsignal_final_genlevelcor_allsyst_upgrade/workspace_preparation

cp workspace_preparation/*pdf ~/public_html/fitsignal_unblinding/fitsignal_final_genlevelcor_allsyst_upgrade/workspace_preparation/ 
cp workspace_preparation/*txt ~/public_html/fitsignal_unblinding/fitsignal_final_genlevelcor_allsyst_upgrade/workspace_preparation/

mkdir ~/public_html/fitsignal_unblinding/fitsignal_final_genlevelcor_allsyst_upgrade/workspace_plots

cp workspace_plots/*pdf ~/public_html/fitsignal_unblinding/fitsignal_final_genlevelcor_allsyst_upgrade/workspace_plots/
cp workspace_plots/*txt ~/public_html/fitsignal_unblinding/fitsignal_final_genlevelcor_allsyst_upgrade/workspace_plots/


mkdir ~/public_html/fitsignal_unblinding/fitsignal_final_genlevelcor_allsyst_upgrade/FOM

cp FOM/*txt ~/public_html/fitsignal_unblinding/fitsignal_final_genlevelcor_allsyst_upgrade/FOM/

mkdir ~/public_html/fitsignal_unblinding/fitsignal_final_genlevelcor_allsyst_upgrade/compare_fits

cp compare_fits/* ~/public_html/fitsignal_unblinding/fitsignal_final_genlevelcor_allsyst_upgrade/compare_fits/
