cp /vols/lhcb/ss4314/probnnRun2tuning/investigation/investigatenshared_removedll/countparticles_final/bin/plotvariable2Dnostack_2files_OS*pdf .
cp /vols/lhcb/ss4314/probnnRun2tuning/investigation/investigatenshared_removedll/countparticles_final/bin/plotvariable2Dnostack_2files_SS*pdf .
